using System.Security.Cryptography;
using System.Text;

namespace MF.Radius.Core.Cryptography;

/// <summary>
/// Provides cryptographic operations for MS-CHAP v2 authentication
/// and MPPE key derivation.
///
/// Fully compliant with:
/// RFC 2759  - MS-CHAPv2
/// RFC 3079  - MPPE Key Derivation
/// RFC 2548  - Microsoft Vendor-Specific RADIUS Attributes
/// </summary>
internal static class RadiusMsChapV2Crypto
{
    
    private static readonly byte[] Magic1 =
        "Magic server to client signing constant"u8.ToArray();

    private static readonly byte[] Magic2 =
        "Pad to make it do more than one iteration"u8.ToArray();

    private static readonly byte[] MagicMppe =
        "Magic client to server master key generating constant"u8.ToArray();

    private static readonly byte[] MagicMppeSend =
        "This is the MS-CHAP v2 send key magic value"u8.ToArray();

    private static readonly byte[] MagicMppeRecv =
        "This is the MS-CHAP v2 receive key magic value"u8.ToArray();

    /// <summary>
    /// 40-byte zero pad (SHSpad1) as defined in RFC 3079.
    /// </summary>
    private static readonly byte[] SHSpad1 = new byte[40];

    /// <summary>
    /// 40-byte 0xF2 pad (SHSpad2) as defined in RFC 3079.
    /// </summary>
    private static readonly byte[] SHSpad2 = CreateShsPad2();

    /// <summary>
    /// Creates and returns a 40-byte array filled with the value 0xF2,
    /// commonly referred to as SHSpad2 in the context of MS-CHAP v2
    /// and defined in RFC 3079 for cryptographic operations.
    /// </summary>
    /// <returns>A byte array of length 40 where each byte is set to 0xF2.</returns>
    private static byte[] CreateShsPad2()
    {
        var arr = new byte[40];
        for (int i = 0; i < 40; i++)
            arr[i] = 0xF2;
        return arr;
    }
    
    /// <summary>
    /// Validates the MS-CHAPv2 response by comparing the client-provided NT response
    /// with the expected NT response derived from the user's stored password,
    /// authenticator challenge, peer challenge, and username.
    /// </summary>
    /// <param name="userName">The username associated with the MS-CHAPv2 authentication attempt.</param>
    /// <param name="storedPassword">The stored password for the user, used to compute the NT hash.</param>
    /// <param name="packetMsChapChallenge">The MS-CHAP challenge value sent by the authenticator.</param>
    /// <param name="peerChallenge">The random challenge value generated by the peer (client).</param>
    /// <param name="clientNtResponse">The NT response provided by the client for verification.</param>
    /// <returns>
    /// True if the client-provided NT response matches the computed NT response; otherwise, false.
    /// </returns>
    public static bool ValidateMsChapV2Response(
        string userName,
        string storedPassword,
        ReadOnlySpan<byte> packetMsChapChallenge,
        ReadOnlySpan<byte> peerChallenge,
        ReadOnlySpan<byte> clientNtResponse
    )
    {
        Span<byte> ntHash = stackalloc byte[16];
        ComputeNtHash(storedPassword, ntHash);

        Span<byte> challengeHash = stackalloc byte[8];
        ComputeChallengeHash(peerChallenge, packetMsChapChallenge, userName, challengeHash);

        Span<byte> expectedNtResponse = stackalloc byte[24];
        ComputeNtResponse(challengeHash, ntHash, expectedNtResponse);

        return clientNtResponse.SequenceEqual(expectedNtResponse);
    }
    
    /// <summary>
    /// Generates the MS-CHAP v2 Authenticator Response based on the provided inputs.
    /// The response is used for validating authentication in MS-CHAP v2 as defined
    /// by RFC 2759. The result is written to the specified destination buffer.
    /// </summary>
    /// <param name="storedPassword">The user's stored plaintext password.</param>
    /// <param name="ident">The identifier used in the MS-CHAP v2 conversation.</param>
    /// <param name="clientNtResponse">The NT Response provided by the client.</param>
    /// <param name="challengeHash">The 8-byte challenge hash derived from the peer and server challenge.</param>
    /// <param name="destination">The buffer where the computed Authenticator Response will be written.
    /// Must have a minimum length of 43 bytes.</param>
    /// <returns>The total number of bytes written to the destination buffer.</returns>
    /// <exception cref="ArgumentException">Thrown when the destination buffer is less than 43 bytes in length.</exception>
    public static int GenerateAuthenticatorResponse(
        string storedPassword,
        byte ident,
        ReadOnlySpan<byte> clientNtResponse,
        ReadOnlySpan<byte> challengeHash,
        Span<byte> destination
    )
    {
        if (destination.Length < 43)
            throw new ArgumentException("Destination must be at least 43 bytes.");

        Span<byte> ntHash = stackalloc byte[16];
        ComputeNtHash(storedPassword, ntHash);

        Span<byte> ntHashHash = stackalloc byte[16];
        Md4Internal.HashData(ntHash, ntHashHash);

        Span<byte> hash = stackalloc byte[20];
        using var sha1 = IncrementalHash.CreateHash(HashAlgorithmName.SHA1);

        // SHA1(NtHashHash + NTResponse + Magic1)
        sha1.AppendData(ntHashHash);
        sha1.AppendData(clientNtResponse);
        sha1.AppendData(Magic1);
        sha1.GetHashAndReset(hash);

        // SHA1(previous + ChallengeHash + Magic2)
        sha1.AppendData(hash);
        sha1.AppendData(challengeHash);
        sha1.AppendData(Magic2);
        sha1.GetHashAndReset(hash);

        destination[0] = ident;
        destination[1] = (byte)'S';
        destination[2] = (byte)'=';

        Convert.TryToHexString(hash, destination[3..], out var written);
        return 3 + written;
    }
    
    /// <summary>
    /// Derives and encrypts MPPE (Microsoft Point-to-Point Encryption) keys based on the provided RADIUS MS-CHAP v2
    /// authentication inputs and writes the resulting keys to the provided destinations.
    /// </summary>
    /// <param name="storedPassword">The user's cleartext password used for NT hash computation.</param>
    /// <param name="clientNtResponse">
    /// A 24-byte NT-Response value produced during the MS-CHAP v2 authentication handshake.
    /// </param>
    /// <param name="requestAuthenticator">
    /// A 16-byte unique Request Authenticator value associated with the RADIUS authentication packet.
    /// </param>
    /// <param name="sharedSecret">
    /// The shared secret between the RADIUS client and server, used for encrypting the MPPE keys.
    /// </param>
    /// <param name="sendKeyDest">
    /// A writable destination span to hold the encrypted MPPE send key (client-to-server encryption key).
    /// Must be large enough to hold the key.
    /// </param>
    /// <param name="recvKeyDest">
    /// A writable destination span to hold the encrypted MPPE receive key (server-to-client encryption key).
    /// Must be large enough to hold the key.
    /// </param>
    /// <exception cref="ArgumentException">
    /// Thrown if <paramref name="clientNtResponse"/> is not 24 bytes or if <paramref name="requestAuthenticator"/>
    /// is not 16 bytes.
    /// </exception>
    public static void GenerateAndEncryptMppeKeys(
        string storedPassword,
        ReadOnlySpan<byte> clientNtResponse,
        ReadOnlySpan<byte> requestAuthenticator,
        string sharedSecret,
        Span<byte> sendKeyDest,
        Span<byte> recvKeyDest
    )
    {
        if (clientNtResponse.Length != 24)
            throw new ArgumentException("NT-Response must be 24 bytes.");

        if (requestAuthenticator.Length != 16)
            throw new ArgumentException("Request Authenticator must be 16 bytes.");

        Span<byte> ntHash = stackalloc byte[16];
        ComputeNtHash(storedPassword, ntHash);

        Span<byte> ntHashHash = stackalloc byte[16];
        Md4Internal.HashData(ntHash, ntHashHash);

        Span<byte> masterKey = stackalloc byte[20];
        using var sha1 = IncrementalHash.CreateHash(HashAlgorithmName.SHA1);

        // MasterKey = SHA1(NtHashHash + NTResponse + MagicMppe)
        sha1.AppendData(ntHashHash);
        sha1.AppendData(clientNtResponse);
        sha1.AppendData(MagicMppe);
        sha1.GetHashAndReset(masterKey);

        // SendKey
        Span<byte> sendKeyFull = stackalloc byte[20];
        sha1.AppendData(masterKey[..16]);
        sha1.AppendData(SHSpad1);
        sha1.AppendData(MagicMppeSend);
        sha1.AppendData(SHSpad2);
        sha1.GetHashAndReset(sendKeyFull);

        // RecvKey
        Span<byte> recvKeyFull = stackalloc byte[20];
        sha1.AppendData(masterKey[..16]);
        sha1.AppendData(SHSpad1);
        sha1.AppendData(MagicMppeRecv);
        sha1.AppendData(SHSpad2);
        sha1.GetHashAndReset(recvKeyFull);

        EncryptMppeKey(sendKeyFull[..16], requestAuthenticator, sharedSecret, sendKeyDest);
        EncryptMppeKey(recvKeyFull[..16], requestAuthenticator, sharedSecret, recvKeyDest);
    }
    
    /// <summary>
    /// Computes the NT (New Technology) hash of a given password and writes the result into the provided span.
    /// </summary>
    /// <param name="storedPassword">The plaintext password for which the NT hash is to be computed.</param>
    /// <param name="ntHash">A span of bytes where the computed NT hash, a 16-byte MD4 hash of the Unicode password, will be written.</param>
    public static void ComputeNtHash(string storedPassword, Span<byte> ntHash)
    {
        ReadOnlySpan<byte> pwdBytes = Encoding.Unicode.GetBytes(storedPassword);
        Md4Internal.HashData(pwdBytes, ntHash);
    }

    /// <summary>
    /// Computes the 8-byte challenge hash used in MS-CHAP v2 authentication.
    /// The hash is derived using a combination of the peer challenge,
    /// the MS-CHAP challenge from the packet, and the user's name,
    /// processed with the SHA-1 hashing algorithm.
    /// </summary>
    /// <param name="peerChallenge">A 16-byte challenge received from the peer.</param>
    /// <param name="packetMsChapChallenge">A 16-byte challenge included in the challenge message from the RADIUS server or authenticator.</param>
    /// <param name="userName">The user's name, which may include a domain prefix (e.g., DOMAIN\username).</param>
    /// <param name="challengeHash">A writable span of 8 bytes where the resulting challenge hash will be stored.</param>
    public static void ComputeChallengeHash(
        ReadOnlySpan<byte> peerChallenge,
        ReadOnlySpan<byte> packetMsChapChallenge,
        string userName,
        Span<byte> challengeHash
    )
    {
        int idx = userName.LastIndexOf('\\');
        string cleanName = idx >= 0 ? userName[(idx + 1)..] : userName;

        using var sha1 = IncrementalHash.CreateHash(HashAlgorithmName.SHA1);
        sha1.AppendData(peerChallenge);
        sha1.AppendData(packetMsChapChallenge);
        sha1.AppendData(Encoding.ASCII.GetBytes(cleanName));

        Span<byte> full = stackalloc byte[20];
        sha1.GetHashAndReset(full);

        full[..8].CopyTo(challengeHash);
    }

    /// <summary>
    /// Computes the NT response for a given challenge hash and NT hash
    /// as specified in MS-CHAP v2 protocol defined in RFC 2759.
    /// The NT response is a 24-byte value derived using DES encryption
    /// with the padded NT hash as the key and the challenge hash as the data.
    /// </summary>
    /// <param name="challengeHash">
    /// An 8-byte challenge hash, calculated from the combination of
    /// peer challenge, MS-CHAP challenge, and username.
    /// </param>
    /// <param name="ntHash">
    /// A 16-byte NT hash derived from the user's password using the MD4 hash algorithm.
    /// </param>
    /// <param name="ntResponse">
    /// A 24-byte output span where the computed NT response will be stored.
    /// </param>
    public static void ComputeNtResponse(
        ReadOnlySpan<byte> challengeHash,
        ReadOnlySpan<byte> ntHash,
        Span<byte> ntResponse
    )
    {
        Span<byte> padded = stackalloc byte[21];
        padded.Clear();
        ntHash.CopyTo(padded);

        EncryptDes(padded[0..7], challengeHash, ntResponse[0..8]);
        EncryptDes(padded[7..14], challengeHash, ntResponse[8..16]);
        EncryptDes(padded[14..21], challengeHash, ntResponse[16..24]);
    }

    /// <summary>
    /// Encrypts an 8-byte block of data using the DES algorithm with a 7-byte key,
    /// applying the MSB-first to LSB transformation to generate the DES-compatible key.
    /// </summary>
    /// <param name="key7">A 7-byte key used to derive the 8-byte DES key.</param>
    /// <param name="data8">An 8-byte block of data to be encrypted.</param>
    /// <param name="destination">A span to store the resulting encrypted 8-byte block.</param>
    private static void EncryptDes(
        ReadOnlySpan<byte> key7,
        ReadOnlySpan<byte> data8,
        Span<byte> destination
    )
    {
        Span<byte> key8 = stackalloc byte[8];

        key8[0] = key7[0];
        key8[1] = (byte)((key7[0] << 7) | (key7[1] >> 1));
        key8[2] = (byte)((key7[1] << 6) | (key7[2] >> 2));
        key8[3] = (byte)((key7[2] << 5) | (key7[3] >> 3));
        key8[4] = (byte)((key7[3] << 4) | (key7[4] >> 4));
        key8[5] = (byte)((key7[4] << 3) | (key7[5] >> 5));
        key8[6] = (byte)((key7[5] << 2) | (key7[6] >> 6));
        key8[7] = (byte)(key7[6] << 1);

        using var des = DES.Create();
        des.Key = key8.ToArray();
        des.TryEncryptEcb(data8, destination, PaddingMode.None, out _);
    }

    /// <summary>
    /// Encrypts the provided MPPE (Microsoft Point-to-Point Encryption) key
    /// using the provided request authenticator and shared secret, and writes
    /// the result to the destination buffer for secure transmission.
    /// </summary>
    /// <param name="key">The original MPPE key to be encrypted, represented as a 16-byte span.</param>
    /// <param name="requestAuthenticator">The request authenticator used as part of the encryption process, represented as a 16-byte span.</param>
    /// <param name="sharedSecret">The shared secret used for creating the encryption hash.</param>
    /// <param name="destination">The destination buffer where the encrypted MPPE key will be written. Must be at least 34 bytes in length.</param>
    private static void EncryptMppeKey(
        ReadOnlySpan<byte> key,
        ReadOnlySpan<byte> requestAuthenticator,
        string sharedSecret,
        Span<byte> destination
    )
    {
        Span<byte> salt = stackalloc byte[2];
        RandomNumberGenerator.Fill(salt);
        salt[0] |= 0x80;

        Span<byte> plaintext = stackalloc byte[32];
        plaintext.Clear();
        plaintext[0] = (byte)key.Length;
        key.CopyTo(plaintext[1..]);

        using var md5 = IncrementalHash.CreateHash(HashAlgorithmName.MD5);
        byte[] secretBytes = Encoding.ASCII.GetBytes(sharedSecret);

        Span<byte> hash = stackalloc byte[16];

        // Block 1
        md5.AppendData(secretBytes);
        md5.AppendData(requestAuthenticator);
        md5.AppendData(salt);
        md5.GetHashAndReset(hash);

        for (int i = 0; i < 16; i++)
            destination[i + 2] = (byte)(plaintext[i] ^ hash[i]);

        // Block 2
        md5.AppendData(secretBytes);
        md5.AppendData(destination.Slice(2, 16));
        md5.GetHashAndReset(hash);

        for (int i = 0; i < 16; i++)
            destination[i + 18] = (byte)(plaintext[i + 16] ^ hash[i]);

        salt.CopyTo(destination[..2]);
    }
    
}
